// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalWebApi.Database;

#nullable disable

namespace MinimalWebApiWithJWT.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20231117212716_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalWebApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "password1",
                            UserName = "john.doe"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Jane",
                            LastName = "Doe",
                            Password = "password2",
                            UserName = "jane.doe"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Alice",
                            LastName = "Smith",
                            Password = "password3",
                            UserName = "alice.smith"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Bob",
                            LastName = "Johnson",
                            Password = "password4",
                            UserName = "bob.johnson"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Eve",
                            LastName = "Brown",
                            Password = "password5",
                            UserName = "eve.brown"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
